name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        swoole: [4.7-php7.4, 4.7-php8.0]
    env:
      POSTGRESQL_VER: f5eda17f89d160d0a89ac7c5db4636bdaefd48e6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: imiphp/swoole
          tags: |
            type=ref,event=branch
            type=raw,${{ matrix.swoole }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_CONTAINER }}
      - name: Push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: swoole.dockerfile
          build-args: |
            SWOOLE_VERSION=${{ matrix.swoole }}
            POSTGRESQL_VER=${{ env.POSTGRESQL_VER }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}